// Mostri iniziali (seed)
export const seedMonsters = [
  { name: 'Goblin', hp: 7, ac: 15, damage: '1d6+2', cr: '1/4', type: 'goblinoid' },
  { name: 'Orco', hp: 30, ac: 13, damage: '1d12+3', cr: '1/2', type: 'humanoid' },
  { name: 'Scheletro', hp: 13, ac: 13, damage: '1d6+2', cr: '1/4', type: 'undead' },
  { name: 'Mago Oscuro', hp: 40, ac: 12, damage: '2d8+3', cr: '2', type: 'humanoid' },
  { name: 'Troll', hp: 84, ac: 15, damage: '2d6+4', cr: '5', type: 'giant' },
  { name: 'Drago Rosso Giovane', hp: 150, ac: 18, damage: '2d10+6', cr: '10', type: 'dragon' },
  { name: 'Lupo Mannaro', hp: 58, ac: 11, damage: '1d8+4', cr: '3', type: 'lycanthrope' },
  { name: 'Ragno Gigante', hp: 26, ac: 14, damage: '1d8+3', cr: '1', type: 'beast' },
  { name: 'Re Lich', hp: 135, ac: 17, damage: '3d8+5', cr: '15', type: 'undead' },
  { name: "Drago d'Oro Antico", hp: 300, ac: 22, damage: '4d12+10', cr: '24', type: 'dragon' },
];

// Campagne e personaggi NON pre-popolati: il DM parte da un DB pulito.
export const seedCampaigns = [];
export const seedCharactersByCampaign = [];
export const seedCampaign = null;
export const seedCharacters = [];

// Incantesimi di esempio
export const seedSpells = [
  {
    name: 'Palla di Fuoco',
    level: 3,
    school: 'Evocazione',
    castingTime: '1 azione',
    range: '150 ft',
    components: 'V, S, M',
    material: 'una pallina di guano di pipistrello e zolfo',
    duration: 'Istantaneo',
    concentration: false,
    ritual: false,
    damage: '8d6',
    saveType: 'Destrezza',
    effect: 'Un punto luminoso schizza dalla tua dita puntate verso un punto che puoi vedere entro gittata e poi esplode con un ruggito sordo in una sfera di fuoco. Ogni creatura nell\'area di effetto di 20 piedi deve effettuare un tiro salvezza su Destrezza. In caso di fallimento subisce 8d6 danni da fuoco, la metà in caso di successo. Il fuoco si diffonde attorno agli angoli. Incendia gli oggetti infiammabili nell\'area che non vengono indossati o trasportati.',
  },
  {
    name: 'Benedizione',
    level: 1,
    school: 'Ammaestramento',
    castingTime: '1 azione bonus',
    range: '30 ft',
    components: 'V, S, M',
    material: 'un po\' di acqua santa',
    duration: '1 minuto',
    concentration: true,
    ritual: false,
    saveType: '',
    effect: 'Benedici fino a tre creature a tua scelta entro gittata. Ogni volta che un bersaglio effettua un tiro per colpire o un tiro salvezza prima che l\'incantesimo termini, il bersaglio può tirare 1d4 e aggiungere il numero ottenuto al tiro per colpire o al tiro salvezza.',
  },
  {
    name: 'Lancia Infuocata',
    level: 2,
    school: 'Evocazione',
    castingTime: '1 azione',
    range: '120 ft',
    components: 'V, S',
    material: '',
    duration: 'Istantaneo',
    concentration: false,
    ritual: false,
    damage: '3d6',
    saveType: 'Destrezza',
    effect: 'Lanci una scintilla di fuoco verso una creatura o un oggetto entro gittata. Effettua un tiro per colpire a distanza con un incantesimo contro il bersaglio. In caso di successo, il bersaglio subisce 3d6 danni da fuoco.',
  },
  {
    name: 'Guarire Ferite',
    level: 1,
    school: 'Invocazione',
    castingTime: '1 azione',
    range: 'Contatto',
    components: 'V, S',
    material: '',
    duration: 'Istantaneo',
    concentration: false,
    ritual: false,
    healing: '1d8+mod',
    saveType: '',
    effect: 'Una creatura che tocchi recupera un numero di punti ferita pari a 1d8 + il tuo modificatore di caratteristica da incantatore. Questo incantesimo non ha effetto sugli undead e sui costrutti.',
  },
  {
    name: 'Invisibilità',
    level: 2,
    school: 'Illusione',
    castingTime: '1 azione',
    range: 'Contatto',
    components: 'V, S, M',
    material: 'un ciglio avvolto in una gomma arabica',
    duration: '1 ora',
    concentration: true,
    ritual: false,
    saveType: '',
    effect: 'Una creatura che tocchi diventa invisibile fino al termine dell\'incantesimo. Qualsiasi cosa il bersaglio indossi o trasporti è invisibile finché rimane addosso alla creatura. L\'incantesimo termina per un bersaglio che attacca o lancia un incantesimo.',
  },
  {
    name: 'Dardo Incantato',
    level: 1,
    school: 'Evocazione',
    castingTime: '1 azione',
    range: '120 ft',
    components: 'V, S',
    material: '',
    duration: 'Istantaneo',
    concentration: false,
    ritual: false,
    damage: '3×(1d4+1)',
    saveType: '',
    effect: 'Crei tre dardi luminosi di forza magica. Ogni dardo colpisce una creatura a tua scelta che puoi vedere entro gittata. Ogni dardo infligge 1d4+1 danni da forza. I dardi colpiscono simultaneamente e puoi dirigerli verso la stessa creatura o verso creature diverse.',
  },
  {
    name: 'Individuazione della Magia',
    level: 1,
    school: 'Divinazione',
    castingTime: '1 azione',
    range: 'Sé stesso',
    components: 'V, S',
    material: '',
    duration: '10 minuti',
    concentration: true,
    ritual: true,
    saveType: '',
    effect: 'Per la durata dell\'incantesimo, percepisci la presenza della magia entro 30 piedi da te. Se percepisci la magia in questo modo, puoi usare la tua azione per vedere un tenue alone attorno a qualsiasi creatura o oggetto visibile nell\'area che porta la magia, e apprendi la sua scuola di magia, se presente.',
  },
  {
    name: 'Danza Macabra',
    level: 3,
    school: 'Necromanzia',
    castingTime: '1 azione',
    range: '60 ft',
    components: 'V, S',
    material: '',
    duration: 'Istantaneo',
    concentration: false,
    ritual: false,
    saveType: 'Costituzione',
    effect: 'Scegli fino a tre cadaveri di umanoidi morti entro gittata. Ogni cadavere si rianima e diventa uno zombie sotto il tuo controllo fino al termine dell\'incantesimo successivo o finché non viene distrutto. Uno zombie animato da questo incantesimo scompare alla fine del tuo prossimo turno.',
  },
  {
    name: 'Volo',
    level: 3,
    school: 'Trasmutazione',
    castingTime: '1 azione',
    range: 'Contatto',
    components: 'V, S, M',
    material: 'una piuma di qualsiasi uccello',
    duration: '10 minuti',
    concentration: true,
    ritual: false,
    saveType: '',
    effect: 'Tocchi una creatura volenterosa. Il bersaglio ottiene una velocità di volo di 60 piedi per la durata dell\'incantesimo. Quando l\'incantesimo termina, il bersaglio cade se si trova ancora in volo, a meno che non possa fermare la caduta.',
  },
];
