// Mostri iniziali
export const seedMonsters = [
  { name: '🧌 Goblin', hp: 7, ac: 15, damage: '1d6+2', cr: '1/4', type: 'goblinoid', xp: 50 },
  { name: '👹 Orco', hp: 30, ac: 13, damage: '1d12+3', cr: '1/2', type: 'humanoid', xp: 100 },
  { name: '💀 Scheletro', hp: 13, ac: 13, damage: '1d6+2', cr: '1/4', type: 'undead', xp: 50 },
  { name: '🧙 Mago Oscuro', hp: 40, ac: 12, damage: '2d8+3', cr: '2', type: 'humanoid', xp: 450 },
  { name: '🗿 Troll', hp: 84, ac: 15, damage: '2d6+4', cr: '5', type: 'giant', xp: 1800 },
  { name: '🐉 Drago Rosso Giovane', hp: 150, ac: 18, damage: '2d10+6', cr: '10', type: 'dragon', xp: 5900 },
  { name: '🐺 Lupo Mannaro', hp: 58, ac: 11, damage: '1d8+4', cr: '3', type: 'lycanthrope', xp: 700 },
  { name: '🕷️ Ragno Gigante', hp: 26, ac: 14, damage: '1d8+3', cr: '1', type: 'beast', xp: 200 },
  { name: '👑 Re Lich', hp: 135, ac: 17, damage: '3d8+5', cr: '15', type: 'undead', xp: 13000 },
  { name: '🐉 Drago d\'Oro Antico', hp: 300, ac: 22, damage: '4d12+10', cr: '24', type: 'dragon', xp: 62000 }
];

// Campagne seed estese
export const seedCampaigns = [
  {
    name: 'La Miniera Perduta di Phandelver',
    description:
      'Una campagna epica per livelli 1-5. I giocatori esplorano le rovine della Miniera Perduta e affrontano il misterioso Magister Nero.',
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    name: 'La Maledizione di Strahd',
    description:
      'Campagna horror gotica per livelli 1-10. I giocatori sono intrappolati nella terra di Barovia, perseguitati dal vampiro Strahd von Zarovich.',
    createdAt: new Date('2024-02-20').toISOString(),
  },
  {
    name: "Le Tombe dell'Annientamento",
    description:
      'Avventura letale per livelli 1-11. Esplorazione della giungla di Chult e della terribile Tomba dei Nove Dei.',
    createdAt: new Date('2024-03-10').toISOString(),
  },
  {
    name: "I Draghi dell'Isola del Tuono",
    description:
      'Campagna per livelli 1-15. I giocatori devono fermare i giganti che minacciano il continente di Faerun.',
    createdAt: new Date('2024-04-05').toISOString(),
  },
  {
    name: 'Acquisiti Incorporati',
    description:
      'Campagna comica per livelli 1-6. I giocatori sono dipendenti di una fantasy corporation che deve espandersi.',
    createdAt: new Date('2024-05-12').toISOString(),
  },
];

// Personaggi seed estesi, raggruppati per campagna
export const seedCharactersByCampaign = [
  {
    campaignName: 'La Miniera Perduta di Phandelver',
    characters: [
      {
        name: 'Thorin Scudodimora',
        class: 'Guerriero',
        level: 3,
        race: 'Nano Montano',
        hp: 45,
        ac: 18,
        strength: 18,
        dexterity: 14,
        constitution: 16,
        wisdom: 12,
        intelligence: 10,
        charisma: 12,
      },
      {
        name: 'Lyra Sottobosco',
        class: 'Ladro',
        level: 3,
        race: 'Halfling',
        hp: 32,
        ac: 15,
        strength: 10,
        dexterity: 18,
        constitution: 14,
        wisdom: 14,
        intelligence: 13,
        charisma: 11,
      },
      {
        name: 'Merlin Ambrosius',
        class: 'Mago',
        level: 3,
        race: 'Umano',
        hp: 28,
        ac: 12,
        strength: 8,
        dexterity: 14,
        constitution: 12,
        wisdom: 13,
        intelligence: 17,
        charisma: 12,
      },
      {
        name: 'Aria Cuor di Vento',
        class: 'Chierico',
        level: 3,
        race: 'Elfo Silvano',
        hp: 38,
        ac: 16,
        strength: 12,
        dexterity: 14,
        constitution: 14,
        wisdom: 16,
        intelligence: 11,
        charisma: 13,
      },
      {
        name: 'Grommash Pugnodiferro',
        class: 'Barbaro',
        level: 3,
        race: 'Mezzorco',
        hp: 52,
        ac: 14,
        strength: 17,
        dexterity: 13,
        constitution: 16,
        wisdom: 10,
        intelligence: 8,
        charisma: 10,
      },
    ],
  },
  {
    campaignName: 'La Maledizione di Strahd',
    characters: [
      {
        name: "Ezmerelda d'Avenir",
        class: 'Ranger',
        level: 5,
        race: 'Vistani',
        hp: 48,
        ac: 16,
        strength: 12,
        dexterity: 18,
        constitution: 14,
        wisdom: 15,
        intelligence: 12,
        charisma: 14,
      },
      {
        name: 'Rudolph van Richten',
        class: 'Chierico',
        level: 5,
        race: 'Umano',
        hp: 42,
        ac: 17,
        strength: 10,
        dexterity: 12,
        constitution: 14,
        wisdom: 18,
        intelligence: 16,
        charisma: 13,
      },
      {
        name: 'Ireena Kolyana',
        class: 'Paladino',
        level: 4,
        race: 'Umano',
        hp: 46,
        ac: 18,
        strength: 16,
        dexterity: 12,
        constitution: 14,
        wisdom: 12,
        intelligence: 10,
        charisma: 16,
      },
      {
        name: 'Ismark Kolyanovich',
        class: 'Guerriero',
        level: 4,
        race: 'Umano',
        hp: 44,
        ac: 16,
        strength: 15,
        dexterity: 14,
        constitution: 15,
        wisdom: 12,
        intelligence: 10,
        charisma: 13,
      },
    ],
  },
  {
    campaignName: "Le Tombe dell'Annientamento",
    characters: [
      {
        name: 'Artus Cimber',
        class: 'Esploratore',
        level: 6,
        race: 'Umano',
        hp: 52,
        ac: 17,
        strength: 14,
        dexterity: 16,
        constitution: 14,
        wisdom: 15,
        intelligence: 13,
        charisma: 12,
      },
      {
        name: 'Dragonbait',
        class: 'Paladino',
        level: 6,
        race: 'Saurial',
        hp: 58,
        ac: 18,
        strength: 17,
        dexterity: 12,
        constitution: 16,
        wisdom: 14,
        intelligence: 10,
        charisma: 15,
      },
      {
        name: 'Mwakambe',
        class: 'Monaco',
        level: 5,
        race: 'Umano Chultano',
        hp: 38,
        ac: 16,
        strength: 12,
        dexterity: 18,
        constitution: 14,
        wisdom: 16,
        intelligence: 11,
        charisma: 10,
      },
    ],
  },
  {
    campaignName: "I Draghi dell'Isola del Tuono",
    characters: [
      {
        name: 'Harshnag the Grim',
        class: 'Barbaro',
        level: 8,
        race: 'Gigante dei Ghiacci',
        hp: 85,
        ac: 15,
        strength: 20,
        dexterity: 12,
        constitution: 18,
        wisdom: 12,
        intelligence: 10,
        charisma: 13,
      },
      {
        name: 'Sirac of Suzail',
        class: 'Paladino',
        level: 7,
        race: 'Mezzelfo',
        hp: 62,
        ac: 19,
        strength: 16,
        dexterity: 10,
        constitution: 14,
        wisdom: 12,
        intelligence: 10,
        charisma: 18,
      },
      {
        name: 'Xanth the Blue',
        class: 'Stregone',
        level: 7,
        race: 'Draconide',
        hp: 44,
        ac: 13,
        strength: 8,
        dexterity: 14,
        constitution: 14,
        wisdom: 12,
        intelligence: 12,
        charisma: 20,
      },
    ],
  },
  {
    campaignName: 'Acquisiti Incorporati',
    characters: [
      {
        name: 'Jim Darkmagic',
        class: 'Mago',
        level: 4,
        race: 'Umano',
        hp: 32,
        ac: 12,
        strength: 8,
        dexterity: 14,
        constitution: 12,
        wisdom: 10,
        intelligence: 18,
        charisma: 16,
      },
      {
        name: 'Omin Dran',
        class: 'Chierico',
        level: 5,
        race: 'Mezzelfo',
        hp: 48,
        ac: 18,
        strength: 14,
        dexterity: 10,
        constitution: 14,
        wisdom: 18,
        intelligence: 13,
        charisma: 14,
      },
      {
        name: 'Binwin Bronzebottom',
        class: 'Guerriero',
        level: 4,
        race: 'Nano',
        hp: 52,
        ac: 17,
        strength: 18,
        dexterity: 12,
        constitution: 16,
        wisdom: 10,
        intelligence: 8,
        charisma: 10,
      },
      {
        name: 'Viari',
        class: 'Ladro',
        level: 4,
        race: 'Elfo',
        hp: 34,
        ac: 16,
        strength: 10,
        dexterity: 18,
        constitution: 12,
        wisdom: 12,
        intelligence: 14,
        charisma: 15,
      },
    ],
  },
];

// Compatibilita' legacy con import esistenti
export const seedCampaign = seedCampaigns[0];
export const seedCharacters = seedCharactersByCampaign[0].characters;

// Incantesimi di esempio
export const seedSpells = [
  { name: 'Palla di Fuoco', level: 3, school: 'Evocazione', damage: '8d6', range: '150 ft', duration: 'Istantaneo' },
  { name: 'Benedizione', level: 1, school: 'Ammaestramento', effect: '+1d4 ai tiri', duration: 'Concentrazione' },
  { name: 'Lancia Infuocata', level: 2, school: 'Evocazione', damage: '3d6', range: '120 ft' },
  { name: 'Guarire Ferite', level: 1, school: 'Invocazione', healing: '1d8+mod', range: 'Contatto' },
  { name: 'Invisibilità', level: 2, school: 'Illusione', duration: '1 ora', range: 'Contatto' }
];